const cities = [
    'East Tateberg',
    'Feeneyland',
    'Dietrichmouth',
    'North Benton',
    'West Guidomouth',
    'Waelchitown',
    'Port Dellaburgh',
    'West Ozellatown',
    'East Coralie',
    'Skilesfurt',
    'Padbergmouth',
    'South Maritza',
    'Wolftown',
    'Lianafort',
    'West Michaleshire',
    'Gaylordberg',
    'New Kathleen',
    'North Akeem',
    'North Alannamouth',
    'Lake Edward',
    'Rhettstad',
    'East Lukaschester',
    'North Sydniview',
    'Hilpertburgh',
    'Lake Violetteshire',
    'South Ramiro',
    'Kilbackport',
    'New Seth',
    'Waltermouth',
    'Port Darrenfort',
    'West Rickeyburgh',
    'Willberg',
    'East Eleanora',
    'Rohanville',
    'Laronville',
    'Port Jerrold',
    'West Doloresshire',
    'Daxton',
    'East Pierre',
    'South Irvingborough',
    'Jaceyside',
    'Jaylinfort',
    'East Cristalbury',
    'Cronamouth',
    'West Rosie',
    'Hahnberg',
    'South Kailyn',
    'Lake Gerdaland',
    'Douglasbury',
    'West Carriefurt',
    'East Gladysborough',
    'West Greysonfort',
    'Howellhaven',
    'Lake Tonymouth',
    'Mannton',
    'South Hudsonport',
    'Lake Kiptown',
    'Lake Lew',
    'Roobchester',
    'Olsonshire',
    'Goldnerview',
    'Evertshire',
    'Brakuschester',
    'Jeanburgh',
    'Harberton',
    'North Angel',
    'Pfefferstad',
    'Kalebshire',
    'East Aliviaborough',
    'South Carleeport',
    'Port Melliebury',
    'New Creola',
    'Leschstad',
    'Bergehaven',
    'New Novellamouth',
    'Port Porterfurt',
    'Fisherview',
    'Fisherburgh',
    'Auershire',
    'Fatimaberg',
    'South Elda',
    'East Aliland',
    'South Claudiehaven',
    'New Sunny',
    'Cummeratafort',
    'Lake Dariofort',
    'East Makenna',
    'Kochtown',
    'West Ashaville',
    'Dietrichport',
    'Aaronville',
    'Weimannborough',
    'Lake Mariellefurt',
    'Flavioborough',
    'East Ryleigh',
    'West Twila',
    'New Tatyana',
    'Port Malindahaven',
    'Emmerichshire',
    'Creminborough'
];
const name = [
    'Bria',
    'Marta',
    'Missouri',
    'Larue',
    'Noemy',
    'Josefa',
    'Rosa',
    'Samara',
    'Lysanne',
    'Pasquale',
    'Jeremy',
    'Lexus',
    'Freida',
    'Rafael',
    'Rubie',
    'Easton',
    'Dustin',
    'Alisa',
    'Clementina',
    'Orion',
    'Santina',
    'Dorcas',
    'Alvah',
    'Rahul',
    'Donato',
    'Barry',
    'Tito',
    'Wayne',
    'Logan',
    'Ocie',
    'Cordell',
    'Horace',
    'Joshua',
    'Francesco',
    'Leora',
    'Armand',
    'Delmer',
    'Gloria',
    'Marcella',
    'Ivory',
    'Dallas',
    'Glennie',
    'Noemie',
    'Shannon',
    'Aracely',
    'Tessie',
    'Herminio',
    'Briana',
    'Benedict',
    'Nathan',
    'Evans',
    'Camilla',
    'Hershel',
    'Titus',
    'Chauncey',
    'Katarina',
    'Sophia',
    'Griffin',
    'Immanuel',
    'Devante',
    'Elissa',
    'Chyna',
    'Danyka',
    'Eli',
    'Maurine',
    'Irving',
    'Kaycee',
    'Maryam',
    'Dayton',
    'Rosemarie',
    'Jewell',
    'Sabryna',
    'Hailie',
    'Luigi',
    'Demond',
    'Cyril',
    'Scotty',
    'Mafalda',
    'Lucienne',
    'Lonny',
    'Herta',
    'Jarred',
    'Johathan',
    'Hadley',
    'Claudine',
    'Toni',
    'Myah',
    'Drake',
    'Pink',
    'Eloise',
    'Krystina',
    'Selmer',
    'Libby',
    'Madisen',
    'Hilma',
    'Lane',
    'Barrett'
];
const surname = [
    'King',
    'Goyette',
    'Purdy',
    'Monahan',
    'Kling',
    'Kreiger',
    'Kuhlman',
    'Denesik',
    'Thiel',
    'Moore',
    'Fisher',
    'Abernathy',
    'Cruickshank',
    'Koch',
    'Gibson',
    'Grady',
    'Aufderhar',
    'Nitzsche',
    'Kiehn',
    'Hackett',
    'Schimmel',
    'Senger',
    'Cormier',
    'Fahey',
    'Fritsch',
    'Hilpert',
    'Sauer',
    'Bernier',
    'Nicolas',
    'Frami',
    'Blick',
    'Harris',
    'Wintheiser',
    'Gaylord',
    'Rau',
    "O'Kon",
    'Rippin',
    'Conn',
    'Abshire',
    'Zemlak',
    'Maggio',
    'Schumm',
    'Thompson',
    'Wiegand',
    'Vandervort',
    'Douglas',
    'Stoltenberg',
    "O'Connell",
    'Yost',
    'Turcotte',
    'Cassin',
    'Schroeder',
    'Adams',
    'Cronin',
    'Keeling',
    'Keebler',
    'Wunsch',
    'Koepp',
    'Howe',
    'Grant',
    'Simonis',
    'Conroy',
    'Murphy',
    'Mitchell',
    'Larkin',
    'Mueller',
    'Emmerich',
    'Stamm',
    'Wilkinson',
    'Lynch',
    'Greenholt',
    'Macejkovic',
    'Kuphal',
    'Schuppe',
    'Runolfsdottir',
    'Ratke',
    'Swift',
    'Spinka',
    'Bergnaum',
    'Ferry',
    'Schaefer',
    "O'Hara",
    'Stiedemann',
    'Champlin',
    'Hand',
    'Orn',
    'Williamson',
    'Green'
];
const products = [
    'Oranges',
    'Apples',
    'Carrots',
    'Bananas',
    'Lemons',
    'Potatoes',
    'Corn',
    'Pea',
    'Tomato'
];

const emails = ["brooke81@garcia.org",
    "troyholland@gmail.com",
    "jennifer30@rocha.biz",
    "robertszachary@gmail.com",
    "ann03@clark.biz",
    "andersonheather@hernandez-gay.com",
    "ndavis@yahoo.com",
    "holtwilliam@jones-weaver.com",
    "howard96@figueroa-davis.com",
    "nicholserik@yahoo.com",
    "ifox@lowe-nelson.biz",
    "aaronweeks@gmail.com",
    "shannon68@yahoo.com",
    "fvelazquez@gmail.com",
    "matthewgoodman@jones.com",
    "vcook@gmail.com",
    "tbarrett@knapp.net",
    "burkecharles@yahoo.com",
    "davisjessica@sullivan.com",
    "jacqueline57@jackson.biz",
    "foleyadam@jones-reed.info",
    "tonidiaz@gmail.com",
    "rebeccajames@colon.com",
    "leslie32@davidson-rodriguez.com",
    "jbeck@garcia.com",
    "william40@hotmail.com",
    "robert08@marshall.com",
    "jason65@hutchinson.net",
    "lucasdavid@hotmail.com",
    "unguyen@miller-ward.com",
];



const randomNumber = (from, to) =>
    Math.floor(Math.random() * (to - from + 1)) + from;

const randomDate = (start, end) =>
    new Date(
        start.getTime() + Math.random() * (end.getTime() - start.getTime())
    );

const randomArray = (length, startNum, endNum) =>
    [...new Array(length)].map(() => randomNumber(startNum, endNum));

const product = () => products[randomNumber(0, products.length - 1)];

const faker = {
    fName: () => name[randomNumber(0, name.length - 1)],
    lName: () => surname[randomNumber(0, surname.length - 1)],
    product: () => products[randomNumber(0, products.length - 1)],
    email: () => emails[randomNumber(0, emails.length - 1)],
    randomWords: length => randomArray(length, 1, 1).map(() => product()),
    randomWord: () => randomArray(1, 1, 1).map(() => product()),
    randomCities: length =>
        randomArray(length, 1, 1).map(
            () => cities[randomNumber(0, cities.length - 1)]
        ),
    randomProducts: () =>
        randomArray(3, 1, 1).map(() => ({
            name: product(),
            count: randomNumber(5, 20)
        }))
};
